In [1]:
# Uncomment the following lines to install the required packages
# %pip install --quiet --upgrade pip
# %pip install --quiet pandas geopandas numpy matplotlib seaborn scikit-learn
# %pip install --quiet plotly plotly_express
# %pip install --quiet nbformat nbconvert ipykernel ipywidgets jupyterlab jupyterlab-git

# Curating Datasets

In [2]:
import pandas as pd
import geopandas as gpd

base_path = 'D:\\tierra\\data\\Lucas\\'

def load_file(file_path):
    # check file extension
    if file_path.endswith('.shp'):
        # Load shapefile using geopandas
        df = gpd.read_file(base_path + file_path)
    elif file_path.endswith('.geojson'):
        # Load GeoJSON file using geopandas
        df = gpd.read_file(base_path + file_path)
    elif file_path.endswith('.csv'):
        # Load CSV file using pandas
        df = pd.read_csv(base_path + file_path)
    else:
        raise ValueError("Unsupported file format: {}".format(file_path))

    return df
def merge_point_id(df1, df2, key1='POINTID', key2='POINTID'):
    if key1 not in df1.columns or key2 not in df2.columns:
        raise ValueError("Both DataFrames must contain a '{}' column.".format(key1))

    merged_df = pd.merge(df1, df2, left_on=key1, right_on=key2, how='outer')
    return merged_df

In [3]:
point_idx = load_file('soil\\LUCAS-SOIL-2018-v2\\LUCAS-SOIL-2018.shp')
point_idx.head()

    POINTID                   geometry
0  47862690  POINT (16.13421 47.15024)
1  47882704  POINT (16.17536 47.27427)
2  47982688  POINT (16.28969 47.12326)
3  48022702  POINT (16.35751 47.24569)
4  48062708  POINT (16.41678 47.29637)

In [4]:
soil_df = load_file('soil\\LUCAS-SOIL-2018-v2\\LUCAS-SOIL-2018.csv')
print(soil_df.columns)

Index(['Depth', 'POINTID', 'pH_CaCl2', 'pH_H2O', 'EC', 'OC', 'CaCO3', 'P', 'N',
       'K', 'OC (20-30 cm)', 'CaCO3 (20-30 cm)', 'Ox_Al', 'Ox_Fe', 'NUTS_0',
       'NUTS_1', 'NUTS_2', 'NUTS_3', 'TH_LAT', 'TH_LONG', 'SURVEY_DATE',
       'Elev', 'LC', 'LU', 'LC0_Desc', 'LC1_Desc', 'LU1_Desc'],
      dtype='object')

In [5]:
bd_2 = load_file('soil\\LUCAS-SOIL-2018-v2\\BulkDensity_2018_final-2.csv')
bd_2.head()

   POINT_ID  BD 0-10  BD 10-20  BD 20-30  BD 0-20
0  30283550    0.219     0.359       NaN    0.289
1  26762002    1.303     1.536       NaN    1.420
2  27842416    0.892     1.018       NaN    0.955
3  26942016    1.068     1.111       NaN    1.089
4  26962018    0.956     1.219       NaN    1.088

In [6]:
merged_df = merge_point_id(soil_df, bd_2, key1='POINTID', key2='POINT_ID')
# drop
merged_df.drop(columns=['POINT_ID'], inplace=True)
merged_df.head()

,Depth,POINTID,pH_CaCl2,pH_H2O,EC,OC,CaCO3,P,N,K,...,Elev,LC,LU,LC0_Desc,LC1_Desc,LU1_Desc,BD 0-10,BD 10-20,BD 20-30,BD 0-20
0,0-20 cm,26521970.0,7.1,7.75,16.83,19,190,< LOD,1.8,461.7,...,181.0,E20,U111,Grassland,Grassland without tree/shrub cover,Agriculture (excluding fallow land and kitchen...,NaN,NaN,NaN,NaN
1,0-20 cm,26581768.0,6.9,7.47,19.44,28.2,204,40.3,3,448.1,...,111.0,E20,U111,Grassland,Grassland without tree/shrub cover,Agriculture (excluding fallow land and kitchen...,1.133,NaN,NaN,NaN
2,0-20 cm,26581792.0,5.8,6.51,11.07,33.5,NaN,< LOD,3,182.8,...,78.0,D20,U420,Shrubland,Shrubland without tree cover,Semi-natural and natural areas not in use,NaN,NaN,NaN,NaN
3,0-20 cm,26581954.0,7.0,7.58,15.71,13.7,10,31.2,1.4,461.7,...,250.0,E30,U112,Grassland,Spontaneously re-vegetated surfaces,Fallow land,NaN,NaN,NaN,NaN
4,0-20 cm,26601784.0,4.5,5.54,5.61,52.1,NaN,< LOD,3.6,161.1,...,145.0,D10,U120,Shrubland,Shrubland with sparse tree cover,Forestry,NaN,NaN,NaN,NaN

In [7]:
org = load_file('soil\\LUCAS-SOIL-2018-v2\\LUCAS2018_ORG.csv')
org.head()

,POINT_ID,SURVEY_SOIL_ORG_CULTIVATED,SURVEY_SOIL_ORG_DEPTH_P_CM,SURVEY_SOIL_ORG_DEPTH_N_CM,SURVEY_SOIL_ORG_DEPTH_E_CM,SURVEY_SOIL_ORG_DEPTH_S_CM,SURVEY_SOIL_ORG_DEPTH_W_CM,SURVEY_SOIL_ORG_DEPTH_P_40_CM,SURVEY_SOIL_ORG_DEPTH_N_40_CM,SURVEY_SOIL_ORG_DEPTH_E_40_CM,SURVEY_SOIL_ORG_DEPTH_S_40_CM,SURVEY_SOIL_ORG_DEPTH_W_40_CM,SURVEY_SOIL_ORG_TAKEN,SURVEY_SOIL_ORG_DEPTH_CANDO
0,27602150,1,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,NaN,1
1,27842394,2,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,1.0,0.0,NaN,1
2,27842416,2,18.0,23.0,NaN,21.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,1
3,27942164,2,23.0,16.0,18.0,20.0,14.0,0.0,0.0,0.0,0.0,0.0,NaN,1
4,28002400,1,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,1.0,0.0,NaN,1

In [8]:
merged_df = merge_point_id(merged_df, org, key1='POINTID', key2='POINT_ID')
# drop
merged_df.drop(columns=['POINT_ID'], inplace=True)
merged_df.head()

,Depth,POINTID,pH_CaCl2,pH_H2O,EC,OC,CaCO3,P,N,K,...,SURVEY_SOIL_ORG_DEPTH_E_CM,SURVEY_SOIL_ORG_DEPTH_S_CM,SURVEY_SOIL_ORG_DEPTH_W_CM,SURVEY_SOIL_ORG_DEPTH_P_40_CM,SURVEY_SOIL_ORG_DEPTH_N_40_CM,SURVEY_SOIL_ORG_DEPTH_E_40_CM,SURVEY_SOIL_ORG_DEPTH_S_40_CM,SURVEY_SOIL_ORG_DEPTH_W_40_CM,SURVEY_SOIL_ORG_TAKEN,SURVEY_SOIL_ORG_DEPTH_CANDO
0,0-20 cm,26521970.0,7.1,7.75,16.83,19,190,< LOD,1.8,461.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0-20 cm,26581768.0,6.9,7.47,19.44,28.2,204,40.3,3,448.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0-20 cm,26581792.0,5.8,6.51,11.07,33.5,NaN,< LOD,3,182.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-20 cm,26581954.0,7.0,7.58,15.71,13.7,10,31.2,1.4,461.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0-20 cm,26601784.0,4.5,5.54,5.61,52.1,NaN,< LOD,3.6,161.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
erosion = load_file('soil\\LUCAS-SOIL-2018-v2\\LUCAS2018_EROSION.csv')
erosion.head()

,POINT_ID,SURVEY_EROSION_SIGNS,SURVEY_EROSION_SHEET,SURVEY_EROSION_SHEET_P,SURVEY_EROSION_SHEET_N,SURVEY_EROSION_SHEET_E,SURVEY_EROSION_SHEET_S,SURVEY_EROSION_SHEET_W,SURVEY_EROSION_SHEET_NR,SURVEY_EROSION_SHEET_N_DIST_M,...,SURVEY_EROSION_WIND_N,SURVEY_EROSION_WIND_E,SURVEY_EROSION_WIND_S,SURVEY_EROSION_WIND_W,SURVEY_EROSION_WIND_NR,SURVEY_EROSION_WIND_N_DIST_M,SURVEY_EROSION_WIND_E_DIST_M,SURVEY_EROSION_WIND_S_DIST_M,SURVEY_EROSION_WIND_W_DIST_M,SURVEY_EROSION_RILLGULLY_N
0,37963072,1,NaN,1.0,0.0,0.0,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,55762590,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,64061606,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,26761786,1,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0
4,26881988,1,NaN,1.0,0.0,0.0,0.0,0.0,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,20.0,NaN,NaN,NaN

In [10]:
merged_df = merge_point_id(merged_df, erosion, key1='POINTID', key2='POINT_ID')
# drop
merged_df.drop(columns=['POINT_ID'], inplace=True)
merged_df.head()

,Depth,POINTID,pH_CaCl2,pH_H2O,EC,OC,CaCO3,P,N,K,...,SURVEY_EROSION_WIND_N,SURVEY_EROSION_WIND_E,SURVEY_EROSION_WIND_S,SURVEY_EROSION_WIND_W,SURVEY_EROSION_WIND_NR,SURVEY_EROSION_WIND_N_DIST_M,SURVEY_EROSION_WIND_E_DIST_M,SURVEY_EROSION_WIND_S_DIST_M,SURVEY_EROSION_WIND_W_DIST_M,SURVEY_EROSION_RILLGULLY_N
0,0-20 cm,26521970.0,7.1,7.75,16.83,19,190,< LOD,1.8,461.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0-20 cm,26581768.0,6.9,7.47,19.44,28.2,204,40.3,3,448.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0-20 cm,26581792.0,5.8,6.51,11.07,33.5,NaN,< LOD,3,182.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-20 cm,26581954.0,7.0,7.58,15.71,13.7,10,31.2,1.4,461.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0-20 cm,26601784.0,4.5,5.54,5.61,52.1,NaN,< LOD,3.6,161.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
bd_df_paper = load_file('bulk_density\\BD2018_data_for_paper.csv')
bd_df_paper.head()

,POINT_ID,LC0_Desc,BDsample_0,coarse_mas,BDfine_0_2,coarse_vol,Unnamed: 6,Unnamed: 7
0,NaN,Land Cover (Eurostat),BDsample_0_20_2018,coarse_mass_fraction,BDfine_0_20_2018_approx,coarse_volume_fraction_approx,NaN,NaN
1,48462776.0,Cropland,1.277,0.09,1.216,0.044,NaN,NaN
2,46662794.0,Woodland,0.895,0.14,0.808,0.048,NaN,NaN
3,46722786.0,Cropland,1.443,0.13,1.353,0.072,NaN,NaN
4,46722792.0,Cropland,1.073,0.16,0.965,0.066,NaN,NaN

In [12]:
merged_df = merge_point_id(merged_df, bd_df_paper, key1='POINTID', key2='POINT_ID')
# drop
merged_df.drop(columns=['POINT_ID'], inplace=True)
merged_df.head()

,Depth,POINTID,pH_CaCl2,pH_H2O,EC,OC,CaCO3,P,N,K,...,SURVEY_EROSION_WIND_S_DIST_M,SURVEY_EROSION_WIND_W_DIST_M,SURVEY_EROSION_RILLGULLY_N,LC0_Desc_y,BDsample_0,coarse_mas,BDfine_0_2,coarse_vol,Unnamed: 6,Unnamed: 7
0,0-20 cm,26521970.0,7.1,7.75,16.83,19,190,< LOD,1.8,461.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0-20 cm,26581768.0,6.9,7.47,19.44,28.2,204,40.3,3,448.1,...,NaN,NaN,NaN,Grassland,1.133,0.14,1.038,0.061,NaN,NaN
2,0-20 cm,26581792.0,5.8,6.51,11.07,33.5,NaN,< LOD,3,182.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-20 cm,26581954.0,7.0,7.58,15.71,13.7,10,31.2,1.4,461.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0-20 cm,26601784.0,4.5,5.54,5.61,52.1,NaN,< LOD,3.6,161.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
bd_shp = load_file('bulk_density\\BD2018_data_for_paper_shapefile\\BD2018_fef_landcover.shp')
bd_shp.head()

,POINT_ID,LC0_Desc,BDsample_0,coarse_mas,BDfine_0_2,coarse_vol,geometry
0,48462776,Cropland,1.2770,0.09,1.215814,0.044204,POINT (17.02603 47.87283)
1,46662794,Woodland,0.8945,0.14,0.808197,0.048165,POINT (14.63887 48.162)
2,46722786,Cropland,1.4430,0.13,1.353031,0.072150,POINT (14.71267 48.08676)
3,46722792,Cropland,1.0725,0.16,0.964561,0.066000,POINT (14.71768 48.14063)
4,46942846,Woodland,0.6035,0.20,0.506304,0.046423,POINT (15.06111 48.61213)

In [14]:
bd_shp.drop(columns=['geometry'], inplace=True)
merged_df = merge_point_id(merged_df, bd_shp, key1='POINTID', key2='POINT_ID')
# drop
merged_df.drop(columns=['POINT_ID'], inplace=True)
merged_df.head()

,Depth,POINTID,pH_CaCl2,pH_H2O,EC,OC,CaCO3,P,N,K,...,coarse_mas_x,BDfine_0_2_x,coarse_vol_x,Unnamed: 6,Unnamed: 7,LC0_Desc,BDsample_0_y,coarse_mas_y,BDfine_0_2_y,coarse_vol_y
0,0-20 cm,26521970.0,7.1,7.75,16.83,19,190,< LOD,1.8,461.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0-20 cm,26581768.0,6.9,7.47,19.44,28.2,204,40.3,3,448.1,...,0.14,1.038,0.061,NaN,NaN,Grassland,1.133,0.14,1.037687,0.061008
2,0-20 cm,26581792.0,5.8,6.51,11.07,33.5,NaN,< LOD,3,182.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-20 cm,26581954.0,7.0,7.58,15.71,13.7,10,31.2,1.4,461.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0-20 cm,26601784.0,4.5,5.54,5.61,52.1,NaN,< LOD,3.6,161.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
texture_shp = load_file('texture\\LUCAS_texture_all\\LUCAS_Texture_all.shp')
texture_shp.head()

,POINTID,NUTS_0,Lucas2009,Lucas2012,Lucas2015,Lucas2018,Coarse,Clay,Sand,Silt,Available,From,USDA,ISSS,geometry
0,90000005,CY,1,0,0,0,18.0,26.0,37.0,37.0,1,2009.0,loam,silty loam,POINT (6483999.623 1662000.119)
1,90000004,CY,1,0,0,0,10.0,22.0,55.0,23.0,1,2009.0,sandy clay loam,loam,POINT (6474000.234 1666000.56)
2,90000003,CY,1,0,0,0,23.0,26.0,46.0,29.0,1,2009.0,sandy clay loam,silty loam,POINT (6470000.088 1664000.465)
3,90000002,CY,1,0,0,0,3.0,56.0,19.0,25.0,1,2009.0,clay,clay,POINT (6481999.946 1663999.855)
4,90000001,CY,1,0,0,0,5.0,43.0,20.0,38.0,1,2009.0,clay,silty clay,POINT (6479999.932 1665999.803)

In [16]:
texture_shp.drop(columns=['geometry'], inplace=True)
merged_df = merge_point_id(merged_df, texture_shp)
merged_df.head()

,Depth,POINTID,pH_CaCl2,pH_H2O,EC,OC,CaCO3,P,N,K,...,Lucas2015,Lucas2018,Coarse,Clay,Sand,Silt,Available,From,USDA,ISSS
0,0-20 cm,26521970.0,7.1,7.75,16.83,19,190,< LOD,1.8,461.7,...,0.0,1.0,NaN,NaN,NaN,NaN,0.0,NaN,None,None
1,NaN,26521974.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,8.0,10.0,76.0,14.0,1.0,2009.0,sandy loam,loamy sand
2,NaN,26561964.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,28.0,41.0,11.0,48.0,1.0,2009.0,silty clay,silty clay
3,0-20 cm,26581768.0,6.9,7.47,19.44,28.2,204,40.3,3,448.1,...,1.0,1.0,14.0,25.0,46.0,29.0,1.0,2009.0,loam,silty loam
4,0-20 cm,26581792.0,5.8,6.51,11.07,33.5,NaN,< LOD,3,182.8,...,1.0,1.0,18.0,26.0,25.0,49.0,1.0,2009.0,loam,silty loam

# Final Dataset

In [17]:
print("Final merged DataFrame shape:", merged_df.shape)
print(merged_df.columns.tolist())

gdf = merge_point_id(merged_df, point_idx)

# convert to GeoDataFrame
gdf = gpd.GeoDataFrame(gdf, geometry='geometry', crs='EPSG:4326')

gdf.head()

Final merged DataFrame shape: (27974, 137)
['Depth', 'POINTID', 'pH_CaCl2', 'pH_H2O', 'EC', 'OC', 'CaCO3', 'P', 'N', 'K', 'OC (20-30 cm)', 'CaCO3 (20-30 cm)', 'Ox_Al', 'Ox_Fe', 'NUTS_0_x', 'NUTS_1', 'NUTS_2', 'NUTS_3', 'TH_LAT', 'TH_LONG', 'SURVEY_DATE', 'Elev', 'LC', 'LU', 'LC0_Desc_x', 'LC1_Desc', 'LU1_Desc', 'BD 0-10', 'BD 10-20', 'BD 20-30', 'BD 0-20', 'SURVEY_SOIL_ORG_CULTIVATED', 'SURVEY_SOIL_ORG_DEPTH_P_CM', 'SURVEY_SOIL_ORG_DEPTH_N_CM', 'SURVEY_SOIL_ORG_DEPTH_E_CM', 'SURVEY_SOIL_ORG_DEPTH_S_CM', 'SURVEY_SOIL_ORG_DEPTH_W_CM', 'SURVEY_SOIL_ORG_DEPTH_P_40_CM', 'SURVEY_SOIL_ORG_DEPTH_N_40_CM', 'SURVEY_SOIL_ORG_DEPTH_E_40_CM', 'SURVEY_SOIL_ORG_DEPTH_S_40_CM', 'SURVEY_SOIL_ORG_DEPTH_W_40_CM', 'SURVEY_SOIL_ORG_TAKEN', 'SURVEY_SOIL_ORG_DEPTH_CANDO', 'SURVEY_EROSION_SIGNS', 'SURVEY_EROSION_SHEET', 'SURVEY_EROSION_SHEET_P', 'SURVEY_EROSION_SHEET_N', 'SURVEY_EROSION_SHEET_E', 'SURVEY_EROSION_SHEET_S', 'SURVEY_EROSION_SHEET_W', 'SURVEY_EROSION_SHEET_NR', 'SURVEY_EROSION_SHEET_N_DIST_M', 'SURVEY_EROSION_SHEET_E_DIST_M', 'SURVEY_EROSION_SHEET_S_DIST_M', 'SURVEY_EROSION_SHEET_W_DIST_M', 'SURVEY_EROSION_RILL', 'SURVEY_EROSION_RILL_P', 'SURVEY_EROSION_RILL_N', 'SURVEY_EROSION_RILL_E', 'SURVEY_EROSION_RILL_W', 'SURVEY_EROSION_RILL_S', 'SURVEY_EROSION_RILL_NR', 'SURVEY_EROSION_RILL_N_DIST_M', 'SURVEY_EROSION_RILL_E_DIST_M', 'SURVEY_EROSION_RILL_S_DIST_M', 'SURVEY_EROSION_RILL_W_DIST_M', 'SURVEY_EROSION_GULLY', 'SURVEY_EROSION_GULLY_P', 'SURVEY_EROSION_GULLY_N', 'SURVEY_EROSION_GULLY_E', 'SURVEY_EROSION_GULLY_S', 'SURVEY_EROSION_GULLY_W', 'SURVEY_EROSION_GULLY_NR', 'SURVEY_EROSION_GULLY_N_DIST_M', 'SURVEY_EROSION_GULLY_E_DIST_M', 'SURVEY_EROSION_GULLY_S_DIST_M', 'SURVEY_EROSION_GULLY_W_DIST_M', 'SURVEY_EROSION_MASS', 'SURVEY_EROSION_MASS_P', 'SURVEY_EROSION_MASS_N', 'SURVEY_EROSION_MASS_E', 'SURVEY_EROSION_MASS_S', 'SURVEY_EROSION_MASS_W', 'SURVEY_EROSION_MASS_NR', 'SURVEY_EROSION_MASS_N_DIST_M', 'SURVEY_EROSION_MASS_E_DIST_M', 'SURVEY_EROSION_MASS_S_DIST_M', 'SURVEY_EROSION_MASS_W_DIST_M', 'SURVEY_EROSION_DEP', 'SURVEY_EROSION_DEP_P', 'SURVEY_EROSION_DEP_N', 'SURVEY_EROSION_DEP_E', 'SURVEY_EROSION_DEP_S', 'SURVEY_EROSION_DEP_W', 'SURVEY_EROSION_DEP_NR', 'SURVEY_EROSION_DEP_N_DIST_M', 'SURVEY_EROSION_DEP_E_DIST_M', 'SURVEY_EROSION_DEP_S_DIST_M', 'SURVEY_EROSION_DEP_W_DIST_M', 'SURVEY_EROSION_WIND', 'SURVEY_EROSION_WIND_P', 'SURVEY_EROSION_WIND_N', 'SURVEY_EROSION_WIND_E', 'SURVEY_EROSION_WIND_S', 'SURVEY_EROSION_WIND_W', 'SURVEY_EROSION_WIND_NR', 'SURVEY_EROSION_WIND_N_DIST_M', 'SURVEY_EROSION_WIND_E_DIST_M', 'SURVEY_EROSION_WIND_S_DIST_M', 'SURVEY_EROSION_WIND_W_DIST_M', 'SURVEY_EROSION_RILLGULLY_N', 'LC0_Desc_y', 'BDsample_0_x', 'coarse_mas_x', 'BDfine_0_2_x', 'coarse_vol_x', 'Unnamed: 6', 'Unnamed: 7', 'LC0_Desc', 'BDsample_0_y', 'coarse_mas_y', 'BDfine_0_2_y', 'coarse_vol_y', 'NUTS_0_y', 'Lucas2009', 'Lucas2012', 'Lucas2015', 'Lucas2018', 'Coarse', 'Clay', 'Sand', 'Silt', 'Available', 'From', 'USDA', 'ISSS']

,Depth,POINTID,pH_CaCl2,pH_H2O,EC,OC,CaCO3,P,N,K,...,Lucas2018,Coarse,Clay,Sand,Silt,Available,From,USDA,ISSS,geometry
0,0-20 cm,26521970.0,7.1,7.75,16.83,19,190,< LOD,1.8,461.7,...,1.0,NaN,NaN,NaN,NaN,0.0,NaN,None,None,POINT (-9.35097 38.89468)
1,NaN,26521974.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,8.0,10.0,76.0,14.0,1.0,2009.0,sandy loam,loamy sand,None
2,NaN,26561964.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,28.0,41.0,11.0,48.0,1.0,2009.0,silty clay,silty clay,None
3,0-20 cm,26581768.0,6.9,7.47,19.44,28.2,204,40.3,3,448.1,...,1.0,14.0,25.0,46.0,29.0,1.0,2009.0,loam,silty loam,POINT (-8.77525 37.1391)
4,0-20 cm,26581792.0,5.8,6.51,11.07,33.5,NaN,< LOD,3,182.8,...,1.0,18.0,26.0,25.0,49.0,1.0,2009.0,loam,silty loam,POINT (-8.83373 37.34975)

In [18]:
# save as geojson
geojson_path = base_path + 'merged_lucas_dataset.geojson'
gdf.to_file(geojson_path, driver='GeoJSON')
print(f"GeoJSON file saved to: {geojson_path}")

# save as CSV
csv_path = base_path + 'merged_lucas_dataset.csv'
gdf.to_csv(csv_path, index=False)
print(f"CSV file saved to: {csv_path}")

GeoJSON file saved to: D:\tierra\data\Lucas\merged_lucas_dataset.geojson
CSV file saved to: D:\tierra\data\Lucas\merged_lucas_dataset.csv